apiVersion: apps/v1
kind: Deployment
metadata:
  name: firstdeployment
  labels:
    env: prod

spec:
  replicas: 2
  selector:
    matchLabels:
      app: testapp

  template:
    metadata:
      name: pod1
      labels:
        app: testapp
    spec:
      containers:
        - name: firstcontainer
          image: vamsi01/javaproject:6
          ports:
            - containerPort: 8080

